package codewing.dao;

/**
 * This bean class is created by CodeWing(version: 1.0).
 * You can change the code generated by changing file 'bean.schema'.
 * This bean class is for database table named 'student'.
 */
public class Student implements java.io.Serializable {

    // All fields:
    //
    private String stuid;
    private String psprtid;
    private String psprtfamily;
    private String psprtname;
    private java.util.Date bthday;
    private String bthplc;
    private Integer colid;
    private Integer majid;
    private Integer majtwid;
    private Integer cntryid;
    private Integer type;
    private Integer stay;
    private Integer sex;
    private Integer fundcome;
    private Integer shrtgrp;
    private Integer fundway;
    private Integer marry;
    private Integer status;
    private java.util.Date apyday;
    private java.util.Date acptday;
    private java.util.Date rprtday;
    private java.util.Date lastreg;
    private java.util.Date eduday;
    private java.util.Date leavday;
    private Integer leavrsn;
    private String school;
    private String address;
    private String phone;
    private String job;
    private String place;
    private String religion;
    private String reportschool;
    private String language;
    private String curplace;
    private String curphone;
    private String chinesename;
    private String CSC;
    private Integer HSK;
    private java.util.Date majorbegin;
    private java.util.Date majorend;
    private String edu;
    private String chineseschool;
    private java.util.Date chinesestart;
    private java.util.Date chineseend;
    private String recommand;
    private String guarantee;
    private String economy;
    private String motherlang;
    private String good;
    private String teacher;
    private String englevel;
    private java.util.Date reportbegin;
    private java.util.Date reportend;
    private String visatype;
    private Integer costdone;
    private String cls;
    private String sendcontry;
    private String sendway;
    private String email;

    /**
     * Empty Constructor for Student.
     */
    public Student() {

    }

    /**
     * Full Constructor for Student.
     */
    public Student(String stuid,String psprtid,String psprtfamily,String psprtname,java.util.Date bthday,String bthplc,Integer colid,Integer majid,Integer majtwid,Integer cntryid,Integer type,Integer stay,Integer sex,Integer fundcome,Integer shrtgrp,Integer fundway,Integer marry,Integer status,java.util.Date apyday,java.util.Date acptday,java.util.Date rprtday,java.util.Date lastreg,java.util.Date eduday,java.util.Date leavday,Integer leavrsn,String school,String address,String phone,String job,String place,String religion,String reportschool,String language,String curplace,String curphone,String chinesename,String CSC,Integer HSK,java.util.Date majorbegin,java.util.Date majorend,String edu,String chineseschool,java.util.Date chinesestart,java.util.Date chineseend,String recommand,String guarantee,String economy,String motherlang,String good,String teacher,String englevel,java.util.Date reportbegin,java.util.Date reportend,String visatype,Integer costdone,String cls,String sendcontry,String sendway,String email) {
        this.stuid = stuid;
        this.psprtid = psprtid;
        this.psprtfamily = psprtfamily;
        this.psprtname = psprtname;
        this.bthday = bthday;
        this.bthplc = bthplc;
        this.colid = colid;
        this.majid = majid;
        this.majtwid = majtwid;
        this.cntryid = cntryid;
        this.type = type;
        this.stay = stay;
        this.sex = sex;
        this.fundcome = fundcome;
        this.shrtgrp = shrtgrp;
        this.fundway = fundway;
        this.marry = marry;
        this.status = status;
        this.apyday = apyday;
        this.acptday = acptday;
        this.rprtday = rprtday;
        this.lastreg = lastreg;
        this.eduday = eduday;
        this.leavday = leavday;
        this.leavrsn = leavrsn;
        this.school = school;
        this.address = address;
        this.phone = phone;
        this.job = job;
        this.place = place;
        this.religion = religion;
        this.reportschool = reportschool;
        this.language = language;
        this.curplace = curplace;
        this.curphone = curphone;
        this.chinesename = chinesename;
        this.CSC = CSC;
        this.HSK = HSK;
        this.majorbegin = majorbegin;
        this.majorend = majorend;
        this.edu = edu;
        this.chineseschool = chineseschool;
        this.chinesestart = chinesestart;
        this.chineseend = chineseend;
        this.recommand = recommand;
        this.guarantee = guarantee;
        this.economy = economy;
        this.motherlang = motherlang;
        this.good = good;
        this.teacher = teacher;
        this.englevel = englevel;
        this.reportbegin = reportbegin;
        this.reportend = reportend;
        this.visatype = visatype;
        this.costdone = costdone;
        this.cls = cls;
        this.sendcontry = sendcontry;
        this.sendway = sendway;
        this.email = email;
    }

    // equals(Just Compare id):
    //
    @Override
    public boolean equals(Object obj) {
        return obj != null &&  obj instanceof Student && (this == obj ||
            this.stuid.equals(((Student) obj).stuid));
    }

    // toString Method
    //
    @Override
    public String toString() {
        return "Student {" +
            "stuid: " + this.stuid + ',' +
            "psprtid: " + this.psprtid + ',' +
            "psprtfamily: " + this.psprtfamily + ',' +
            "psprtname: " + this.psprtname + ',' +
            "bthday: " + this.bthday + ',' +
            "bthplc: " + this.bthplc + ',' +
            "colid: " + this.colid + ',' +
            "majid: " + this.majid + ',' +
            "majtwid: " + this.majtwid + ',' +
            "cntryid: " + this.cntryid + ',' +
            "type: " + this.type + ',' +
            "stay: " + this.stay + ',' +
            "sex: " + this.sex + ',' +
            "fundcome: " + this.fundcome + ',' +
            "shrtgrp: " + this.shrtgrp + ',' +
            "fundway: " + this.fundway + ',' +
            "marry: " + this.marry + ',' +
            "status: " + this.status + ',' +
            "apyday: " + this.apyday + ',' +
            "acptday: " + this.acptday + ',' +
            "rprtday: " + this.rprtday + ',' +
            "lastreg: " + this.lastreg + ',' +
            "eduday: " + this.eduday + ',' +
            "leavday: " + this.leavday + ',' +
            "leavrsn: " + this.leavrsn + ',' +
            "school: " + this.school + ',' +
            "address: " + this.address + ',' +
            "phone: " + this.phone + ',' +
            "job: " + this.job + ',' +
            "place: " + this.place + ',' +
            "religion: " + this.religion + ',' +
            "reportschool: " + this.reportschool + ',' +
            "language: " + this.language + ',' +
            "curplace: " + this.curplace + ',' +
            "curphone: " + this.curphone + ',' +
            "chinesename: " + this.chinesename + ',' +
            "CSC: " + this.CSC + ',' +
            "HSK: " + this.HSK + ',' +
            "majorbegin: " + this.majorbegin + ',' +
            "majorend: " + this.majorend + ',' +
            "edu: " + this.edu + ',' +
            "chineseschool: " + this.chineseschool + ',' +
            "chinesestart: " + this.chinesestart + ',' +
            "chineseend: " + this.chineseend + ',' +
            "recommand: " + this.recommand + ',' +
            "guarantee: " + this.guarantee + ',' +
            "economy: " + this.economy + ',' +
            "motherlang: " + this.motherlang + ',' +
            "good: " + this.good + ',' +
            "teacher: " + this.teacher + ',' +
            "englevel: " + this.englevel + ',' +
            "reportbegin: " + this.reportbegin + ',' +
            "reportend: " + this.reportend + ',' +
            "visatype: " + this.visatype + ',' +
            "costdone: " + this.costdone + ',' +
            "cls: " + this.cls + ',' +
            "sendcontry: " + this.sendcontry + ',' +
            "sendway: " + this.sendway + ',' +
            "email: " + this.email + ',' +
            "}";
    }

    // Setter and Getter Method
    //
    public void setstuid(String stuid) {
        this.stuid = stuid;
    }

    public String getstuid() {
        return this.stuid;
    }

    public void setpsprtid(String psprtid) {
        this.psprtid = psprtid;
    }

    public String getpsprtid() {
        return this.psprtid;
    }

    public void setpsprtfamily(String psprtfamily) {
        this.psprtfamily = psprtfamily;
    }

    public String getpsprtfamily() {
        return this.psprtfamily;
    }

    public void setpsprtname(String psprtname) {
        this.psprtname = psprtname;
    }

    public String getpsprtname() {
        return this.psprtname;
    }

    public void setbthday(java.util.Date bthday) {
        this.bthday = bthday;
    }

    public java.util.Date getbthday() {
        return this.bthday;
    }

    public void setbthplc(String bthplc) {
        this.bthplc = bthplc;
    }

    public String getbthplc() {
        return this.bthplc;
    }

    public void setcolid(Integer colid) {
        this.colid = colid;
    }

    public Integer getcolid() {
        return this.colid;
    }

    public void setmajid(Integer majid) {
        this.majid = majid;
    }

    public Integer getmajid() {
        return this.majid;
    }

    public void setmajtwid(Integer majtwid) {
        this.majtwid = majtwid;
    }

    public Integer getmajtwid() {
        return this.majtwid;
    }

    public void setcntryid(Integer cntryid) {
        this.cntryid = cntryid;
    }

    public Integer getcntryid() {
        return this.cntryid;
    }

    public void settype(Integer type) {
        this.type = type;
    }

    public Integer gettype() {
        return this.type;
    }

    public void setstay(Integer stay) {
        this.stay = stay;
    }

    public Integer getstay() {
        return this.stay;
    }

    public void setsex(Integer sex) {
        this.sex = sex;
    }

    public Integer getsex() {
        return this.sex;
    }

    public void setfundcome(Integer fundcome) {
        this.fundcome = fundcome;
    }

    public Integer getfundcome() {
        return this.fundcome;
    }

    public void setshrtgrp(Integer shrtgrp) {
        this.shrtgrp = shrtgrp;
    }

    public Integer getshrtgrp() {
        return this.shrtgrp;
    }

    public void setfundway(Integer fundway) {
        this.fundway = fundway;
    }

    public Integer getfundway() {
        return this.fundway;
    }

    public void setmarry(Integer marry) {
        this.marry = marry;
    }

    public Integer getmarry() {
        return this.marry;
    }

    public void setstatus(Integer status) {
        this.status = status;
    }

    public Integer getstatus() {
        return this.status;
    }

    public void setapyday(java.util.Date apyday) {
        this.apyday = apyday;
    }

    public java.util.Date getapyday() {
        return this.apyday;
    }

    public void setacptday(java.util.Date acptday) {
        this.acptday = acptday;
    }

    public java.util.Date getacptday() {
        return this.acptday;
    }

    public void setrprtday(java.util.Date rprtday) {
        this.rprtday = rprtday;
    }

    public java.util.Date getrprtday() {
        return this.rprtday;
    }

    public void setlastreg(java.util.Date lastreg) {
        this.lastreg = lastreg;
    }

    public java.util.Date getlastreg() {
        return this.lastreg;
    }

    public void seteduday(java.util.Date eduday) {
        this.eduday = eduday;
    }

    public java.util.Date geteduday() {
        return this.eduday;
    }

    public void setleavday(java.util.Date leavday) {
        this.leavday = leavday;
    }

    public java.util.Date getleavday() {
        return this.leavday;
    }

    public void setleavrsn(Integer leavrsn) {
        this.leavrsn = leavrsn;
    }

    public Integer getleavrsn() {
        return this.leavrsn;
    }

    public void setschool(String school) {
        this.school = school;
    }

    public String getschool() {
        return this.school;
    }

    public void setaddress(String address) {
        this.address = address;
    }

    public String getaddress() {
        return this.address;
    }

    public void setphone(String phone) {
        this.phone = phone;
    }

    public String getphone() {
        return this.phone;
    }

    public void setjob(String job) {
        this.job = job;
    }

    public String getjob() {
        return this.job;
    }

    public void setplace(String place) {
        this.place = place;
    }

    public String getplace() {
        return this.place;
    }

    public void setreligion(String religion) {
        this.religion = religion;
    }

    public String getreligion() {
        return this.religion;
    }

    public void setreportschool(String reportschool) {
        this.reportschool = reportschool;
    }

    public String getreportschool() {
        return this.reportschool;
    }

    public void setlanguage(String language) {
        this.language = language;
    }

    public String getlanguage() {
        return this.language;
    }

    public void setcurplace(String curplace) {
        this.curplace = curplace;
    }

    public String getcurplace() {
        return this.curplace;
    }

    public void setcurphone(String curphone) {
        this.curphone = curphone;
    }

    public String getcurphone() {
        return this.curphone;
    }

    public void setchinesename(String chinesename) {
        this.chinesename = chinesename;
    }

    public String getchinesename() {
        return this.chinesename;
    }

    public void setCSC(String CSC) {
        this.CSC = CSC;
    }

    public String getCSC() {
        return this.CSC;
    }

    public void setHSK(Integer HSK) {
        this.HSK = HSK;
    }

    public Integer getHSK() {
        return this.HSK;
    }

    public void setmajorbegin(java.util.Date majorbegin) {
        this.majorbegin = majorbegin;
    }

    public java.util.Date getmajorbegin() {
        return this.majorbegin;
    }

    public void setmajorend(java.util.Date majorend) {
        this.majorend = majorend;
    }

    public java.util.Date getmajorend() {
        return this.majorend;
    }

    public void setedu(String edu) {
        this.edu = edu;
    }

    public String getedu() {
        return this.edu;
    }

    public void setchineseschool(String chineseschool) {
        this.chineseschool = chineseschool;
    }

    public String getchineseschool() {
        return this.chineseschool;
    }

    public void setchinesestart(java.util.Date chinesestart) {
        this.chinesestart = chinesestart;
    }

    public java.util.Date getchinesestart() {
        return this.chinesestart;
    }

    public void setchineseend(java.util.Date chineseend) {
        this.chineseend = chineseend;
    }

    public java.util.Date getchineseend() {
        return this.chineseend;
    }

    public void setrecommand(String recommand) {
        this.recommand = recommand;
    }

    public String getrecommand() {
        return this.recommand;
    }

    public void setguarantee(String guarantee) {
        this.guarantee = guarantee;
    }

    public String getguarantee() {
        return this.guarantee;
    }

    public void seteconomy(String economy) {
        this.economy = economy;
    }

    public String geteconomy() {
        return this.economy;
    }

    public void setmotherlang(String motherlang) {
        this.motherlang = motherlang;
    }

    public String getmotherlang() {
        return this.motherlang;
    }

    public void setgood(String good) {
        this.good = good;
    }

    public String getgood() {
        return this.good;
    }

    public void setteacher(String teacher) {
        this.teacher = teacher;
    }

    public String getteacher() {
        return this.teacher;
    }

    public void setenglevel(String englevel) {
        this.englevel = englevel;
    }

    public String getenglevel() {
        return this.englevel;
    }

    public void setreportbegin(java.util.Date reportbegin) {
        this.reportbegin = reportbegin;
    }

    public java.util.Date getreportbegin() {
        return this.reportbegin;
    }

    public void setreportend(java.util.Date reportend) {
        this.reportend = reportend;
    }

    public java.util.Date getreportend() {
        return this.reportend;
    }

    public void setvisatype(String visatype) {
        this.visatype = visatype;
    }

    public String getvisatype() {
        return this.visatype;
    }

    public void setcostdone(Integer costdone) {
        this.costdone = costdone;
    }

    public Integer getcostdone() {
        return this.costdone;
    }

    public void setcls(String cls) {
        this.cls = cls;
    }

    public String getcls() {
        return this.cls;
    }

    public void setsendcontry(String sendcontry) {
        this.sendcontry = sendcontry;
    }

    public String getsendcontry() {
        return this.sendcontry;
    }

    public void setsendway(String sendway) {
        this.sendway = sendway;
    }

    public String getsendway() {
        return this.sendway;
    }

    public void setemail(String email) {
        this.email = email;
    }

    public String getemail() {
        return this.email;
    }
}